#!/usr/bin/env bash

set -uo pipefail

declare -ri TRUE=0
declare -ri FALSE=1

declare -r PROGRAM_PATH="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &> /dev/null && pwd)"
declare -r COLORSCHEME_DIR="${PROGRAM_PATH}/colorscheme"
declare -r COLORSCHEME_SOURCE="./terminal-colorscheme.json"

test ! -d "$COLORSCHEME_DIR" && mkdir "$COLORSCHEME_DIR"

get_json_values(){
	echo "$(jq -crM "${@}" "$COLORSCHEME_SOURCE")"
}

get_hex_colors(){
	local indexes=""

	for i in $(seq 0 15); do
		indexes+=".[$i][0]"

		if [[ $i -ne 15 ]]; then
			indexes+=", "
		fi
	done

	local output=("$(get_json_values "$indexes")")
	echo ${output[@]}
}

get_dec_colors(){
	local indexes=""

	for i in $(seq 0 15); do
		for j in 0 1 2; do
			indexes+=".[$i][1][$j]"

			if [[ $j -ne 2 ]]; then
				indexes+=", "
			fi
		done

		if [[ $i -ne 15 ]]; then
			indexes+=", "
		fi
	done

	local -ra values=( $(get_json_values "$indexes") )
	local formatedValues=()
	local -i count=0
	local cur=""

	for curValue in ${values[@]}; do
		cur+="$curValue"

		if [[ $count -lt 2 ]]; then
			cur+=","
			count+=1
			continue
		fi

		count=0
		formatedValues+=("$cur")
		cur=""
	done

	echo ${formatedValues[@]}
}

qterminal(){
	local -ra colors=($(get_dec_colors))

	echo -e "[General]
Description=DuckAfire Terminal Colorscheme

[Background]
Color=${colors[0]}

[BackgroundIntense]
Color=${colors[0]}

[Foreground]
Color=${colors[15]}

[ForegroundIntense]
Color=${colors[15]}

[Color0]
Color=${colors[0]}

[Color0Intense]
Color=${colors[8]}

[Color1]
Color=${colors[1]}

[Color1Intense]
Color=${colors[9]}

[Color2]
Color=${colors[2]}

[Color2Intense]
Color=${colors[10]}

[Color3]
Color=${colors[3]}

[Color3Intense]
Color=${colors[11]}

[Color4]
Color=${colors[4]}

[Color4Intense]
Color=${colors[12]}

[Color5]
Color=${colors[5]}

[Color5Intense]
Color=${colors[13]}

[Color6]
Color=${colors[6]}

[Color6Intense]
Color=${colors[14]}

[Color7]
Color=${colors[7]}

[Color7Intense]
Color=${colors[15]}
" > "$COLORSCHEME_DIR/da-qterminal.colorscheme"

	# - rw- r-- r--
	chmod 644 "$COLORSCHEME_DIR/da-qterminal.colorscheme"
}

qterminal
