#!/usr/bin/env bash

declare -r vimrc="$HOME/.vimrc"
declare -r backup="./my-vimrc.vim"

if [[ ! -f "$vimrc" ]]; then
	echo "Configuration file ('~/.vimrc') not found!"
	exit 1
fi

cp "$vimrc" "$backup"

exit 0
