extension = mbstring
; `exif` requires mbstring:
extension = exif
extension = ctype
extension = iconv
extension = json
extension = fileinfo
extension = gettext
extension = tokenizer
extension = phar
extension = intl
extension = zip
