; PDO drivers
extension = pdo
extension = pdo_mysql
extension = pdo_pgsql
extension = pdo_sqlite
extension = pdo_firebird
extension = pdo_oci
extension = pdo_odbc

; Direct drivers
extension = mysqli
extension = pgsql
extension = sqlite3
extension = oci8_12c
extension = oci8_19
extension = odbc
