#!/usr/bin/env sh

DIR="$(dirname "$(realpath "$0")")"
VIMRC_SRC="$DIR/vimrc"
VIMRC_DEST="$HOME/.vimrc"

if [ -f "$VIMRC_DEST" ]
then
	echo 'This will REPLACE your vimrc!
Do you want to continue?
  Yes [Enter]
  No  [^C]'
	read placeholder
	unset placeholder
fi

cp "$VIMRC_SRC" "$VIMRC_DEST"
