[PHP]

; * ERROR_LOG;
; * ERROR_REPORTING;
; * EXTENSIONS_DIR;
; * FILE_UPLOADS;
; * OPEN_BASEDIR;
; * OUTPUT_BUFFERING;
; * OUTPUT_HANDLER;
; * URL_REWRITER_HOSTS;
; * URL_REWRITER_TAGS;
; * ZEND_EXCEPTION_IGNORE_ARGS;
; * ZLIB_OUTPUT_COMPRESSION;
; * ZLIB_OUTPUT_COMPRESSION_LEVEL; and
; * ZLIB_OUTPUT_HANDLER.

;;;;;;;;;;;;;;;;;;;;
; php.ini Options  ;
;;;;;;;;;;;;;;;;;;;;

user_ini.filename = .php.ini
user_ini.cache = 3600

;;;;;;;;;;;;;;;;;;;;
; Language Options ;
;;;;;;;;;;;;;;;;;;;;

; Enable PHP under Apache:
engine = On

; Disable ONLY <? ?>
; (<?= ?> always is on):
short_open_tag = Off

; Maximum "length" of a floating
; point number:
precision = 14

; Maximum size of a output data
; (excluding headers and cookers)
; PHP should keep internally before
; pushing that data to the client
; (if it is exceded, PHP will send
; that data in chunks of roughly
; this size):
;
; NOTE: it can be controlled via
; Output Buffering Control functions.
output_buffering = ${OUTPUT_BUFFERING}

; A function to handler scripts output:
;
; NOTE: preper to use the function
; `ob_start` (it makes your code
; independent of the php.ini).
;
; NOTE: you cannot use both `mb_output_handler`
; and `ob_iconv_handler` as output handler
; simultaneously (it can be done through of
; `output_handler = mb_output_handler` directive
; and `ob_start("ob_iconv_handler")` call,
; and vice versa).
;
; NOTE: you cannot use both
; `output_handler = ob_gzhandler`
; and `zlib.output_compression = On`.
;
; NOTE: `output_handler` always must
; be empty if `zlib.output_compressin = On`;
; if you still need of a handler while
; use zlib, use `zlib.output_handler`.
output_handler = ${OUTPUT_HANDLER}

; Comma-separated list of tags and
; attributes (<tagName>=[attributeName])
; that have to receive the Session ID
; as suffix (PHP will intercept the output
; and will apply the changes):
url_rewriter.tags = ${URL_REWRITER_TAGS}

; Comma-separated list of safe domains that
; have to be receive the Session ID:
;
; NOTE: if this is empty and url_rewrite.tags
; is not empty, all URL will receive the
; Session ID, what it can a BIG problem.
url_rewriter.hosts = ${URL_REWRITER_HOSTS}

; Comporess output using zlib library:
zlib.output_compression = ${ZLIB_OUTPUT_COMPRESSION}

; (-1: auto)
; https://deepwiki.com/zlib-ng/zlib-ng/13.1-compression-level-selection#configuration-table
zlib.output_compression_level = ${ZLIB_OUTPUT_COMPRESSION_LEVEL}

; It works like `output_handler`, but in a
; different order:
;
; NOTE: You cannot specify additional output
; handlers if `zlib..output_compression == On`.
zlib.output_handler = ${ZLIB_OUTPUT_HANDLER}

; Auto-flush output layer after every output block
; (it is equal call `flush()` after use `echo` or
; `print`; or after a block of HTML code):
;
; NOTE:  Printing empty strings or sending headers
; is not considered output and will not result in
; a flush operation.
implicit_flush = Off

; Function that will be called when the `unserialize`
; function finds an undefined class that should be
; instantiated.
;
; NOTE: it only will receive the class name
; (string) as argument.
;
; NOTE: if it is not defined or if the function
; does not include/implement the missin class, a
; warning will be shown.
unserialize_callback_func =

; Maximum depth of the `unserialize` function inputs.
;
; NOTE: 0 disable this limitator.
unserialize_max_depth = 1024

; Enable automatic precision to serialization process
; of floating point numbers (data will not be lost):
;
; NOTE: it also is used by the function `json_encode`.
serialize_precision = 0

; Colon-separated list (or semicolon-separated list, in
; Windows) of directory trees which content can be access
; by PHP.
;
; NOTE: symbolic link cannot be used to get around this.
open_basedir = ${OPEN_BASEDIR}

; Comma-separated list of functions names:
disable_functions =

; Comma-separated list of classes names:
disable_classes =

; Colors of snippets highlighted (with HTML)
; by the function `highlight_string` and
; `highlight_file`:
; (Pink, gray, yellow, white, and dark-gray.)
highlight.string  = #e237aa
highlight.comment = #797979
highlight.keyword = #e6ba0b
highlight.default = #dbdbdb
highlight.html    = #4a4a4a

; Users cannot abort a request after start it.
ignore_user_abort = On

; Used to improve the performance in application
; that need to be open a lot of files.
;
; NOTE: use `open_basedir__ disable this cache.
realpath_cache_size = 1024k

; Time To Live, in seconds, of the file real file
; path cache.
; (Using 24h.)
realpath_cache_ttl = 86400

; Enable PHP garbage collector:
zend.enable_gc = On

; If enabled, sscripts may be written in encoding
; that are incompatible with the PHP scanner (like
; CP9356).
;
; NOTE: it requires to enable the mbstirng extension.
zend.multibytes = Off

; It allow to set the default enconfig for the scritps.
;
; NOTE: `declare(encoding=...)` overrides this.
;
; NOTE: it requires to set of `zend.multibytes`.
zend.script_encoding =

; Show/hide the values given as arguments to function/
; methods in exception stacktrace.
zend.exception_ignore_args = ${ZEND_EXCEPTION_IGNORE_ARGS}

; Maximum length of a string used as argument to a
; function/method.
zend.exception_string_param_max_len = 50

;;;;;;;;;;;;;;;;;
; Miscellaneous ;
;;;;;;;;;;;;;;;;;

; Add to header a field that indicates PHP is being used
; by the server.
expose_php = Off

;;;;;;;;;;;;;;;;;;;
; Resource Limits ;
;;;;;;;;;;;;;;;;;;;

; Maximum execution time of each script, in seconds.
;
; NOTE: this time is not affected by system calls,
; stream operations, data bank queries, ...; except
; on Windows (where the real time is measured).
;
; NOTE: this is hardcoded to `0` for the CLI.
max_exception_time = 2

; Maximum time, in seconds, PHP can use to interpreter
; input datas, like GET and POST.
;
; (stopwatch starts when PHP is called by the server
; and stop when the execution starts.)
;
; NOTE: -1 sets the value of `max_exception_time`.
max_input_time = -1

; Maximum nesting level of super globals:
max_input_nesting_level = 8

; Maximum of input variables that can be accept by
; $_GET, $_POST, and $_COOKIE (applied individually)
; in the same request:
max_input_vars = 20

; Maximum of input variables and file uploads that can
; be accepted in the same request:
;
; NOTE: -1 is equal `max_input_vars` + `max_file_uploads`.
max_multipart_body_parts = -1

memory_limit = 64M

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Error handling and logging ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

; Which errors are show by PHP:
; E_ALL               all errors and warnings;
; E_ERROR             fatal run-time errors;
; E_RECOVERABLE_ERROR almost datal run-time errors;
; E_WARNING           non-fatal run-time errors;
; E_PARSE             compile-time parse errors;
; E_NOTICE            run-time notices (warnings which often result
;                     from bug in your code, but it is possible that
;                     is was intentional);
; E_STRICT            suggestions to the source code;
; E_CORE_ERROR        fatal errors during PHP's initial startup;
; E_CORE_WARNING      non-fatal errors during PHP's initial startup;
; E_COMPILE_ERROR     fatal compile-time errors;
; E_COMPILE_WARNING   non-fatal compile-time errors;
; E_USER_ERROR        user-generated error messages;
; E_USER_WARNING      user-generated warning messages;
; E_USER_NOTICE       user-generated notice messages;
; E_DEPRECATED        warning related to deprecated code; and
; E_USER_DEPRECATED   user-generated deprecation warnings.
;
; NOTE: common values:
;  * E_ALL (All.)
;  * E_ALL & ~E_NOTICE (All, except notices.)
;  * E_ALL & ~E_NOTICE & ~E_STRICT (All, except notices and code recomendations.)
;  * E_COMPILE_ERROR|E_RECOVERABLE|E_ERROR|E_CORE_ERROR (Only errors.)
error_reporting = ${ERROR_REPORTING}

; Destine of error messages:
;
; (It can be `Off`, `stderr` (affects only CGI/CLI
; binaries), or `On` (or `stdout`).
display_errors = stderr

; (Startup errors are separated of other ones.)
display_startup_errors = Off

; Whether PHP have to use a log file:
log_errors = On

; Ignore repeated (from any script) errors or
; messages.
ignore_repeated_errors = Off
ignore_repeated_source = Off

report_memleaks = On

; Show information related to the internal stat of
; the Zend Engine:
;
; (Useful to "core developers".)
report_zend_debug = 0

; Configurations of XML-RPC PECL (since PHP 8)
; extension.
;xmlrpc_error_number =
;xmlrpc_error_number =

; Add HTML tags to error messages (it includes
; links to documentation pages):
;
; NOTE: this is hardcoded to `Off` for the CLI.
html_errors = Off

; Document references (root and files extension)
; used by `html_errors` to created link to PHP's
; documentation:
docref_root =
docref_ext  =

; Prefix/suffix of error messages:
error_prepend_string =
error_append_string  =

error_log = ${ERROR_LOG}

; Prefix to every message logged to syslog:
syslog.ident = php

; What type of program is logging the message:
syslog.facility = user

; Characted allow in logs:
;
; (It can be `ascii` to all pritable ASCII
; characters and NL; `no-ctrl` to all characters
; except control characters; `all` to all
; characters; or `raw` to all, but without split
; messages with new lines.)
syslog.filter = ascii

;;;;;;;;;;;;;;;;;
; Data Handling ;
;;;;;;;;;;;;;;;;;

; The separator used in PHP generated URLs to
; separate arguments:
; (Using `&`.)
arg_separator.output = "&amp;"

; List of separator(s) used by PHP to parse
; input URLs into variables:
arg_separator.input = "&"

; Determine which super global array will be
; registered when PHP starts up; the options
; are: G(et), P(ost), C(ookie), E(nv), or
; S(erver).
;
; NOTE: prefer to use the function `getenv` instead
; of `$_ENV`.
variables_order = "GPCS"

; Determine which super global data should be registered
; into $_REQUEST (it supports only G, P, and C):
;
; NOTE: if empty, the value of `variables_order` will be
; used.
request_order = "GP"

; Disable PHP registers: $argc; anc $argv.
register_argc_argv = Off

; If enabled, $_ENV, $_REQUEST, and $_SERVER only will be
; created after their first use.
;
; NOTE: `register_argc_argv` must be disabled for this
; directive to have any effect.
auto_globals_jit = On

; Enable $_POST and $_FILES (they will be empty):
enable_post_data_reading = On

; (`0` disable this limitator.)
post_max_size = 4M

; Set files that must be automatically parsed before/after
; of the main file (like it is loaded with `require`):
;
; NOTE: if the function (language constructor before PHP 8.4)
; `exit` is called by the main file, "suffix file" will not
; be runned.
auto_prepend_file = None
auto_append_file  = None

; Default value to Content-Type (from data headers):
;
; NOTE: it can be defined in runtime with the function `header`.
default_mimetype = "text/html"

; Encoding of PHP scripts:
default_charset = "UTF-8"

; Enconding used by functions used to manage multibyte strings;
; to process input data; and to process output data:
;
; NOTE: if empty, value of `default_charset` will be used.
;
; NOTE: they are deprecated; use only `default_charset`.
internal_encoding =
input_encoding    =
output_encoding   =

;;;;;;;;;;;;;;;;;;;;;;;;;
; Paths and Directories ;
;;;;;;;;;;;;;;;;;;;;;;;;;

; Colon-separated list of directories that are used by some
; keywords and functions to search for files which specified
; path is not absolute:
include_path = ".:/usr/share/php83"

; PHP's root directory:
;
; NOTE: it only will be used if non-empty.
doc_root =

; Individual directory (present in all users home) that stores
; PHP scripts that will be runned when a request is done to a
; URL which URI starts with an user name (like
; `https://example.com/~foouser/bar.php`; where `bar.php` will
; be searched inside the directory specified by `user_dir`, that
; must be inside the home directory of the `foouser` user):
user_dir =

; Where PHP will search by dynamically loaded extensions:
extension_dir = "${EXTENSIONS_DIR}"

; Where PHP should put temporary files.
sys_temp_dir = "/tmp"

; Disable function `dl`:
;
; NOTE: this is disabled in multuthreaded servers.
enable_dl = Off

; Prevent that URL can be used to access PHP directly:
cgi.force_redirect = On

; Disable forced return of the HTTP Status 200:
cgi.nph = Off

; Name of the environment variable used by PHP, when
; `cgi.force_redirect = On`, to check if the binary is
; being called directly by a client (through of an URL):
;
; NOTE: default is `REDIRECT_STATUS` (used by Apache).
cgi.redirect_status_env =

; Define that PHP must try to fix the URL when it is
; ambiguous:
;
; NOTE: the URL is given (to PHP) by the WEB server.
;
; NOTE: the success of this attempt defines the values
; of `SCRIPT_FILENAME`, `PATH_INFO`, and `PATH_TRANSLATED`
; based on the result.
;
; NOTE: e.g., if PHP receive `https://foo.bar/dir/file.php/stuff`,
; PHP will try to find `stuff`, if it does not exist, it will
; try to find `file.php`, ...; if the file exists, it will be
; executed.
cgi.fix_pathinfo = Off

; Define that PHP must discard the file path given by the WEB
; server; having to trust only in SCRIPT_FILEPATH and PATH_INFO:
cgi.discard_path = On

; Define that PHP must not impersonate security tokens of the
; calling client:
;
; NOTE: it does not work in POSIX OS ones.
fastcgi.impersonate = Off

; Disable logging through FastCGI connection:
fastcgi.loggin = Off

; Type of headers to use when sending HTTP responde code
; (`Off` is a header RFC-3875, that is compatible with
; Apache; `On` is a header RFC-2616):
cgi.rfc2616_headers = Off

; Define CGI PHP must check whether the script starts with
; a shebang (if yes, this line will be completely ignored
; and will not be appended in the output):
cgi.check_shebang_line = On

;;;;;;;;;;;;;;;;
; File Uploads ;
;;;;;;;;;;;;;;;;

; Whether to allow HTTP file uploads:
file_uploads = ${FILE_UPLOADS}

; Temporary directory for HTTP uploaded files:
;
; NOTE: it will use `sys_temp_dir`.
upload_tmp_dir =

; Maximum allowed size for uploaded files:
upload_max_filesize = 2M

; Maximum number of files that can be uploaded via a single
; request:
max_file_uploads = 5

;;;;;;;;;;;;;;;;;;
; Fopen wrappers ;
;;;;;;;;;;;;;;;;;;

; Allow treatment of URLs as files:
allow_url_fopen = Off

; Allow `include`/`require` to open URLs as files:
allow_url_include = Off

; Define the anonymous FTP password:
from =

; Value of User-Agent (header field):
user_agent =

; Timeout, in seconds, for socket based streams:
default_socket_timeout = 60

; Define PHP must not check dynamically the sequence of
; characters used to indicate the end of a line (useful
; when a project uses files created in different OS ones):
auto_detect_line_ending = Off

