#!/usr/bin/env bash

# Dependences:
# * upower >=0.99.n
# * notify-send >=0.7.n

# BATtery Observer v0.0.2
#
# MIT License
#
# Copyright (c) 2025 DuckAfire <duckafire.github.io/nest>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

declare -ri TRUE=0
declare -ri FALSE=1

declare -ri LOW_BATTERY_LEVEL=15
declare -ri CRITICAL_BATTERY_LEVEL=5

declare -r CHECKING_INTERVAL="1m"
declare -r NOTIFICATION_EXPIRE_TIME="60000" # 1m

declare -r FULL_BATTERY_ICON="battery-full-charged-symbolic.svg"
declare -r LOW_BATTERY_ICON="battery-caution-symbolic.svg"
declare -r CRITICAL_BATTERY_ICON="battery-empty-symbolic.svg"

declare BATTERY_DEVICE="$(upower --enumerate | grep --perl-regexp --ignore-case '.*devices.*battery.*')"

get_battery_info()
{
	echo "$(upower --show-info "$BATTERY_DEVICE" | grep --perl-regexp --only-matching "$1")"
}

get_battery_percentage()
{
	echo "$(get_battery_info 'percentage: *\K\d+')"
	# cat "./percentage" # NOTE: it simulates the percentage of the battery charge. Use this to debug.
}

is_battery_charging()
{
	if [[ "$(get_battery_info 'state: *\K(dis)?charging')" = "discharging" ]]
	# if [[ "$(cat "./charging")" = "discharging" ]] # NOTE: it simulates the charging status of the battery. Use this to debug.
	then
		return $FALSE
	fi

	# it can be: charging or fully-charged
	return $TRUE
}

push_notification()
{
	# "full" by default
	local level="low"
	local icon="$FULL_BATTERY_ICON"
	local message="Full battery. You can disconnect the charger."

	case "$1" in
		"low")
			level="normal"
			icon="$LOW_BATTERY_ICON"
			message="Low battery level ($battery_percentage%). Please connect the charger."
		;;
		"critical")
			level="critical"
			icon="$CRITICAL_BATTERY_ICON"
			message="CRITICAL battery level ($battery_percentage%). Connect the charger!"
		;;
	esac

	notify-send --urgency="$level" --expire-time="$NOTIFICATION_EXPIRE_TIME" --app-name="BATO" --icon="$icon" --category="warning" "$message"
}

# "mutable variables"
declare -i full_battery_warned=$FALSE
declare -i low_level_battery_warned=$FALSE
declare -i critical_level_battery_warned=$FALSE
declare -i battery_percentage=-1

while true
do
	if is_battery_charging
	then
		low_level_battery_warned=$FALSE
		critical_level_battery_warned=$FALSE

		if [[ $full_battery_warned -eq $FALSE ]] && [[ "$(get_battery_percentage)" -eq 100 ]]
		then
			push_notification "full"
			full_battery_warned=$TRUE

		fi
	elif [[ $low_level_battery_warned -eq $FALSE ]] || [[ $critical_level_battery_warned -eq $FALSE ]]
	then
		full_battery_warned=$FALSE
		battery_percentage=$(get_battery_percentage)

		if [[ $critical_level_battery_warned -eq $FALSE ]] && [[ $battery_percentage -le $CRITICAL_BATTERY_LEVEL ]]
		then
			push_notification "critical"
			low_level_battery_warned=$TRUE
			critical_level_battery_warned=$TRUE

		elif [[ $low_level_battery_warned -eq $FALSE ]] && [[ $battery_percentage -le $LOW_BATTERY_LEVEL ]]
		then
			push_notification "low"
			low_level_battery_warned=$TRUE
		fi
	fi

	# NOTE (debug message): it displays the value of the "mutable variables".
	# clear
	# echo -e "full: $full_battery_warned"'\n'"low : $low_level_battery_warned"'\n'"crit: $critical_level_battery_warned"'\n'"perc: $battery_percentage%"'\n'

	sleep "$CHECKING_INTERVAL"
done
