#!/usr/bin/env bash

if [[ $# -eq 0 ]]; then
	echo "Lorem ipsum odor amet, consectetuer adipiscing elit. Potenti ultricies inceptos, quam facilisis aliquam vehicula quis. Laoreet proin magna inceptos senectus lorem. Penatibus etiam metus quam sodales nisi. Pellentesque mattis ligula habitasse sed eleifend massa hendrerit accumsan. Venenatis sed penatibus justo sagittis laoreet malesuada elementum. Auctor adipiscing conubia phasellus; aptent habitasse accumsan. Diam inceptos finibus magna imperdiet gravida molestie consequat himenaeos. Imperdiet suscipit natoque sem tellus ut; vel urna. Vulputate cubilia sodales risus at eget et sociosqu lacus commodo."
else
	echo "Lorem ipsum odor amet, consectetuer adipiscing elit.
Potenti ultricies inceptos, quam facilisis aliquam vehicula
quis. Laoreet proin magna inceptos senectus lorem. Penatibus
etiam metus quam sodales nisi. Pellentesque mattis ligula
habitasse sed eleifend massa hendrerit accumsan. Venenatis
sed penatibus justo sagittis laoreet malesuada elementum.
Auctor adipiscing conubia phasellus; aptent habitasse accumsan.
Diam inceptos finibus magna imperdiet gravida molestie consequat
himenaeos. Imperdiet suscipit natoque sem tellus ut; vel urna.
Vulputate cubilia sodales risus at eget et sociosqu lacus commodo."
fi
