#!/usr/bin/env sh

# Templates Preprocessor

HELP_MSG='tp <file> <key0=value0> [...] [keyN=valueN]
... | tp <key0=value0> [...] [keyN=valueN]

It replaces the keys, found in the given file, with
their respective values; result in putted on stdout.
'

if [ $# -eq 0 ]
then
	echo "$HELP_MSG"
	exit 0
fi

#############
# TODO
if [ -t 0 ]; then
    echo "Executado DIRETAMENTE (sem pipeline)."
else
    echo "Executado via PIPELINE (ou redirecionamento de entrada)."
    # Exemplo: ler o conteúdo vindo do pipe
    while read -r linha; do
        echo "Recebido: $linha"
    done
fi
#############

if [ $# -lt 2 ]
then
	echo "$HELP_MSG" 1>&2
	exit 1
fi

INPUT_FILE="$1"

if [ ! -f "$INPUT_FILE" ]
then
	echo "Invalid file: $INPUT_FILE" 1>&2
	exit 1
fi

expression=""

shift

for pair in $@
do
	# 0 - key=value
	# 0 - key
	# 0 - value
	#
	# 1 - key=value=value
	# 1 - key
	# 1 - value=value
	key="${pair%%=*}"
	value="${pair#*=}"

	expression="${expression}s/\\\${$key}/$value/;"
done

sed "$expression" "$INPUT_FILE"

