#!/usr/bin/env bash

echo -e "Bold:   \e[30m⬤  \e[31m⬤  \e[32m⬤  \e[33m⬤  \e[34m⬤  \e[35m⬤  \e[36m⬤  \e[37m⬤ \e[0m"
echo -e "Normal: \e[90m⬤  \e[91m⬤  \e[92m⬤  \e[93m⬤  \e[94m⬤  \e[95m⬤  \e[96m⬤  \e[97m⬤ \e[0m"
